version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio_datalake
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.1-python3.10
    container_name: airflow_maestro
    depends_on:
      - minio
      - postgres
    ports:
      - "8080:8080"
    environment:
      # AQUI ESTÁ A CORREÇÃO MÁGICA: Mudou de CORE para DATABASE
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_REQUIREMENTS=requests boto3 pandas pyarrow s3fs python-dotenv
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./.env:/opt/airflow/.env
    # AQUI MUDAMOS O INIT PARA MIGRATE
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Admin --lastname Admin --role Admin --email admin@example.com --password admin && airflow webserver & airflow scheduler"
volumes:
  minio_data:
  postgres_data: